# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4d1d601dae6c253054c4837d708777d97753894d231e1a56b92dd0d54ca00e6c52d32dd1762534fd93a0722ed9b5caa5c8563ac3b5b2d09678492670f6dfb8f4

test:
  secret_key_base: 15241696b0a54360a4fa9b64425712b97bcc263cfc1da9741f2cbaa05440d8708bdf7a034211d79433afc1c24375f637dc4b84766606ae7a2855ddcdec8ce7be

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
